name: application_koperasi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.19.0
  syncfusion_flutter_gauges: ^27.1.57
  collection: ^1.18.0
  device_preview: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/kemdikbud.png
    - assets/img/koperasi.png
    - assets/img/polinema.png
    - assets/img/man.png

  #fonts:
  # - family: Poppins
    #  fonts:
      #   - asset: fonts/Poppins-Regular.ttf
      #  - asset: fonts/Poppins-Bold.ttf
      #    weight: 700
